---
title: "Premier League 2023-24 Season Analysis"
author: "Hari Krishna"
format: 
  dashboard:
    orientation: rows
    theme: sky
server: shiny
---

```{r warning=FALSE}
#| context: setup
source("R/libraries.R")
source("R/draw_graph.R")
source("R/get_data.R")
source("R/table_report.R")
source("R/season_level_Stats.R")

match_results_data<-read.csv("data/match_results_data.csv")
final_pl_table<-read.csv("data/final_pl_table.csv")
final_pl_table<-sparklines_logic(match_data = match_results_data,final_pl_table = final_pl_table)

```



# {.sidebar}

```{r}
shiny::selectInput('selectteam', 'Select Team',choices=unique(match_results_data$Home))
br()
shiny::selectInput('selectmatch', 'Select Match',choices=NULL)
```

```{r}
#| context: server


observe({
   req(input$selectteam)
   shiny::updateSelectInput(session,"selectmatch",choices =get_match_details(match_results_data,team_select=input$selectteam))
})


output$plot<-renderPlotly({
  draw_event_graph(match_url = input$selectmatch,data_hex = hex_codes)
  
}) %>% shiny::bindCache(input$selectmatch)

output$table<-renderReactable({
  
  match_report(match_url = input$selectmatch)
  
}) %>% shiny::bindCache(input$selectmatch)


output$season_stats<-renderReactable({
  season_level_stats(final_pl_table)
})


```



# Match Level Stats

```{r}
#| title: "Events wrt time plot"
shinycssloaders::withSpinner(plotlyOutput('plot',width ='100%',height='100%'),type=2,color.background = "orange")
```

```{r}
#| title: "Match Report Table"
shinycssloaders::withSpinner(reactable::reactableOutput("table"),type=2,color.background = "orange")
```

<!-- ### Column -->

<!-- ```{r} -->
<!-- #| title: "Match Report Table" -->
<!-- reactable::reactable(iris) -->
<!-- ``` -->




# Season Level Stats

## Row
```{r}
#| title: "Match Report Table"
shinycssloaders::withSpinner(reactable::reactableOutput("season_stats"),type=2,color.background = "orange")
```


# About




